### ISSUE TITLE
block/allow IP-addresses from specific countries

### ISSUE THREAD

**Issue by raymond-de** [codeling/bfstop#104]
Hello,

coult you implement the feature, that only a specific country (with their IP-addresses) could allow to login?

I don't know if this feature is a good one for bfstop or another plugin (do you writing such other plugins?)

kind regards,
Raymond

**Comment by codeling** [comment]
Making this a hard restriction doesn't feel right to me - it would mean that if your users are e.g. on vacation or working abroad, they couldn't log in.

What I am thinking of is making this information part of a system that adapts the number of allowed login attempts (see https://github.com/codeling/bfstop/issues/76). Does this sound like it could be useful for you?

There also seems to be a (commercial) plugin available already: http://extensions.joomla.org/profile/extension/access-a-security/site-access/geoblocker

**Comment by codeling** [comment]
@raymond-de I'll close this issue in favor of #76. In case you don't think #76 is sufficient, please comment here.
