### ISSUE TITLE
Range of IP addresses

### ISSUE THREAD

**Issue by photman52** [codeling/bfstop#105]
Hi
is there any way I can block a range of ip addresses without putting them in individually
ie 189.119.222.01 to 189.119.222.255

thanks

Photman52

**Comment by codeling** [comment]
Yes you can do that, just enter the subnet you want to block in CIDR notation, e.g. 189.119.222.1/24 in the example you gave.

Supported since bfstop v1.2 (see https://github.com/codeling/bfstop/issues/52)

**Comment by photman52** [comment]
Thank you very much

Great Product

**Comment by photman52** [comment]
Hi

Wonder if you can help please..

I was entering a range of IP addresses to block and now I cannot get in myself no matter which IP address I use

How do I disable BF Stop



Thanks

Bob

**Comment by codeling** [comment]
Sorry missed that last message before. To unblock yourself: https://github.com/codeling/bfstop/wiki/FAQ#what-can-i-do-in-case-i-have-locked-myself-out

**Comment by photman52** [comment]
Hi thanks for that. 
I have been trying to block a range of ip address ie 188.234.0.2/255 
But when i do this it blocks everyone out
What am I doing wrong please
Bob

**Comment by codeling** [comment]
Please check the correct syntax for the CIDR suffix notation. The number after the slash specifies the number of bits of the address to consider as mask. The whole IP address is only 32 bits long; so 
/255 is too large a number. I don't know why it would block every IP then, and will look into that.

What address range are you trying to block exactly? If for example 188.234.0.0-188.234.0.255, then specify "188.234.0.0/24" (every number in between the dots has 8 bits, so /24 means "take the first 3 numbers as mask"). 188.234.0.0/16 would block everything from 188.234.0.0-188.234.255.255

**Comment by photman52** [comment]
Hi
This has sorted it

Thank you

Bob
