### ISSUE TITLE
Clearing failed logins table?

### ISSUE THREAD

**Issue by jgold723** [codeling/bfstop#110]
How do I clear the table for failed login attempts? Or perhaps limit the number of failed login attempts that this keeps? In the week we've had this running, it's recorded nearly 3,000 failed logins (some kind of bot banging at the door) and I can see at some point this table is going to become ridiculously large and probably cause some performance issues.

OOPS, never mind. I found the "Prune" option in the system plugin settings. 

Many thanks for this -- it's proving to be very helpful.

**Comment by codeling** [comment]
solved, closing.
