### ISSUE TITLE
Blank IP block?

### ISSUE THREAD

**Issue by andrewm57** [codeling/bfstop#111]
I've used this plugin across many sites, hosts, Joomla versions, etc, and it's worked fine until today. I received an email (below) about a 5 attempt block today, and later on I discovered that everybody was blocked, front & back. The oddity is that the IP field is blank - first time I've seen that.

The same info from the email is in the Failed Logins & the 'blank' IP is Blocked (expiring in 24 hours)  from the BFStop Component menu. The failed logins are also in the Joomla error log, and again the IP is missing. The BFStop log was set only to errors, and is empty.

I recovered the site with the FTP file name change, but am wondering 1) why would the IP field be blank, and 2) why would that block everything.
## Username                  IP-Address      Date and time        Origin  

admin                                     2015-12-19 14:23:45  Backend 
admin                                     2015-12-19 14:23:51  Backend 
admin                                     2015-12-19 14:23:57  Backend 
admin                                     2015-12-19 14:24:02  Backend 
admin                                     2015-12-19 14:24:08  Backend

**Comment by codeling** [comment]
Seems that the client somehow managed to make bfstop unable to determine the IP address.
At this moment I cannot tell you why this is the case. Could you check whether bfstop has written any additional information in a log file (in your joomla log file directory)?

It definitely sounds like a bug. By the way, the method to determine the IP address was changed since the last release, see here: https://github.com/codeling/bfstop/commit/f3b476888e461c0d4b33f26135d35d894410a72a . This might have fixed the problem, but I can't tell you for sure.

In any case, there should be a check for this condition, and bfstop should then do no blocking.

**Comment by andrewm57** [comment]
Joomla itself couldn't get the IP address, since it was also reported as 
failed logins at /log/error.php

/log/plg_system_bfstop.log.php had nothing but the file header comments. 
I had the plugin set to only log errors.

FWIW, this is on J3.4.5 (yes I know, upgrade) and BFStop 1.3.0 (I had to 
check the XML file, the version isn't reported in the plugin or 
component UI).

My client changed his password to the host server. I'm trying to get 
that so I can grab the POSTS from the access logs and check the error logs.

Thank you,
Andrew MacMillen
--------------------------------
HawkFeather Web Design & Hosting
http://www.hawkfeather.com/
360-779-4097

**Comment by andrewm57** [comment]
Got the access log. Bizarre, because it's showing the IP. Here's the relevant hits. A GET, then 5 POSTS, then more 403/blocked POSTS. So it did what it's supposed to do.

179.216.46.24 - - [19/Dec/2015:14:23:40 -0500] "GET /administrator/index.php HTTP/1.1" 200 5776 "-" "Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5)"
179.216.46.24 - - [19/Dec/2015:14:23:45 -0500] "POST /administrator/index.php HTTP/1.1" 303 5 "-" "Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5)"
179.216.46.24 - - [19/Dec/2015:14:23:46 -0500] "POST /administrator/index.php HTTP/1.1" 200 6057 "-" "Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5)"
179.216.46.24 - - [19/Dec/2015:14:23:51 -0500] "POST /administrator/index.php HTTP/1.1" 303 5 "-" "Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5)"
179.216.46.24 - - [19/Dec/2015:14:23:51 -0500] "POST /administrator/index.php HTTP/1.1" 200 6057 "-" "Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5)"
179.216.46.24 - - [19/Dec/2015:14:23:57 -0500] "POST /administrator/index.php HTTP/1.1" 303 5 "-" "Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5)"
179.216.46.24 - - [19/Dec/2015:14:23:57 -0500] "POST /administrator/index.php HTTP/1.1" 200 6057 "-" "Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5)"
179.216.46.24 - - [19/Dec/2015:14:24:02 -0500] "POST /administrator/index.php HTTP/1.1" 303 5 "-" "Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5)"
179.216.46.24 - - [19/Dec/2015:14:24:03 -0500] "POST /administrator/index.php HTTP/1.1" 200 6057 "-" "Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5)"
179.216.46.24 - - [19/Dec/2015:14:24:08 -0500] "POST /administrator/index.php HTTP/1.1" 303 5 "-" "Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5)"
179.216.46.24 - - [19/Dec/2015:14:24:09 -0500] "POST /administrator/index.php HTTP/1.1" 403 117 "-" "Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5)"
179.216.46.24 - - [19/Dec/2015:14:24:09 -0500] "POST /administrator/index.php HTTP/1.1" 403 117 "-" "Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5)"
179.216.46.24 - - [19/Dec/2015:14:24:09 -0500] "POST /administrator/index.php HTTP/1.1" 403 117 "-" "Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5)"
179.216.46.24 - - [19/Dec/2015:14:24:10 -0500] "POST /administrator/index.php HTTP/1.1" 403 117 "-" "Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5)"
179.216.46.24 - - [19/Dec/2015:14:24:10 -0500] "POST /administrator/index.php HTTP/1.1" 403 117 "-" "Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5)"
179.216.46.24 - - [19/Dec/2015:14:24:10 -0500] "POST /administrator/index.php HTTP/1.1" 403 117 "-" "Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5)"
179.216.46.24 - - [19/Dec/2015:14:24:11 -0500] "POST /administrator/index.php HTTP/1.1" 403 117 "-" "Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5)"
179.216.46.24 - - [19/Dec/2015:14:24:11 -0500] "POST /administrator/index.php HTTP/1.1" 403 117 "-" "Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5)"
179.216.46.24 - - [19/Dec/2015:14:24:11 -0500] "POST /administrator/index.php HTTP/1.1" 403 117 "-" "Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5)"
179.216.46.24 - - [19/Dec/2015:14:24:11 -0500] "POST /administrator/index.php HTTP/1.1" 403 117 "-" "Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5)"
179.216.46.24 - - [19/Dec/2015:14:24:12 -0500] "POST /administrator/index.php HTTP/1.1" 403 117 "-" "Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5)"
179.216.46.24 - - [19/Dec/2015:14:24:12 -0500] "POST /administrator/index.php HTTP/1.1" 403 117 "-" "Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5)"
179.216.46.24 - - [19/Dec/2015:14:24:12 -0500] "POST /administrator/index.php HTTP/1.1" 403 117 "-" "Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5)"
179.216.46.24 - - [19/Dec/2015:14:24:13 -0500] "POST /administrator/index.php HTTP/1.1" 403 117 "-" "Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5)"
179.216.46.24 - - [19/Dec/2015:14:24:13 -0500] "POST /administrator/index.php HTTP/1.1" 403 117 "-" "Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5)"
179.216.46.24 - - [19/Dec/2015:14:24:13 -0500] "POST /administrator/index.php HTTP/1.1" 403 117 "-" "Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5)"
179.216.46.24 - - [19/Dec/2015:14:24:14 -0500] "POST /administrator/index.php HTTP/1.1" 403 117 "-" "Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5)"
179.216.46.24 - - [19/Dec/2015:14:24:14 -0500] "POST /administrator/index.php HTTP/1.1" 403 117 "-" "Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5)"

**Comment by codeling** [comment]
Has this happened again since?
Did you also happen to get a more detailed bfstop log for a time when this happened?
Have you tried if the change I posted above fixes the problem?
Since I cannot reproduce this at the moment, the only thing I can do is build in safe-guards so that empty IPs are not written to the database and do not block everything.

**Comment by andrewm57** [comment]
This has not reoccurred.
Per the original, the bfstop log was blank from the incident. The Joomla error log showed the failed logins with a blank IP. The Apache access logs had the IP.
I didn't see any changes you recommended.

**Comment by codeling** [comment]
> I didn't see any changes you recommended.

> It definitely sounds like a bug. By the way, the method to determine the IP address was changed since the last release, see here: f3b4768 . This might have fixed the problem, but I can't tell you for sure.

**Comment by andrewm57** [comment]
I don't see a new release to install. The latest in CHANGELOG says 1.3.0 and I have 1.4.0, plus the source files don't like they've been changed recently.

I'm not a coder, but I can edit files or upload changed files if I know what to do, or hopefully have a package to install.

**Comment by codeling** [comment]
Correct, there was no release yet. The changes were just made here in the repository so far, and would require manual file changes.

If you want to try nevertheless, you see the changes that were done when you click on the link I provided (green lines were added, red lines removed; the main part is the addition of lines in the getIPAddr() function).

**Comment by codeling** [comment]
I have added a check, so that even in case all the methods to determine an IP fail (for which I have yet to determine a possible reason), an empty IP address will not be entered into a blocklist.
