### ISSUE TITLE
Notice: Undefined offset

### ISSUE THREAD

**Issue by boldc** [codeling/bfstop#115]
Joomla 3.4.1 (I cannot upgrade to latest Joomla due to unrelated extension conflict)
BFstop 1.3.0

1) Added IP address to whitelist in backend
2) Clicked on the listing for this entry in the backend whitelist
3) Result:

Notice: Undefined offset: 1 in /home/mywebsite/public_html/administrator/components/com_bfstop/helpers/phpwhois/whois.ip.php on line 103
Unexpected error

I am not sure how this notice impacts the whitelist entry (whether or not an exception is made for users logging in from the IP address that was added)

**Comment by codeling** [comment]
I cannot reproduce this at the moment, but I will look into it. It should not affect the effectivity of the whitelisting, the information shown when clicking on the IP is just for detail.

**Comment by boldc** [comment]
Thanks! Further observation confirms that the whitelist appears to be functioning on my site despite error notice.

**Comment by codeling** [comment]
phpWhois will be removed in 1.4.0, so this issues should not occur again with the new version (to appear in a few days).
