### ISSUE TITLE
Update server doesn't work

### ISSUE THREAD

**Issue by fippu82** [codeling/bfstop#116]
I get the error that the update server can't be contacted. It seems down.

**Comment by codeling** [comment]
Thanks for reporting. It's a known issue: https://github.com/codeling/bfstop/issues/95
In short: will be fixed with a next release (which will need to be installed manually), I'll ping you here once a next release is available!

**Comment by codeling** [comment]
@fippu82 There is a new release available, it should address this issue: https://github.com/codeling/bfstop/releases/tag/1.4.1
The new update URL is https://bfstop.bfroehler.info/update.xml
The easiest way to upgrade is probably to install the pkg_bfstop-1.4.1.zip file via the backend!

Please comment here or open a new issue if you should still encounter any problems with that new version!
