### ISSUE TITLE
Problem with ipv6 addresses

### ISSUE THREAD

**Issue by kauffeld** [codeling/bfstop#117]
ipv6 addresses seem to work correctly, however I have problems with ipv6 CIDR addresses. Addresses with numbers greater than 32 make the system fail. Addresses such as 2218 2a03:b780:1:2::/64 can be entered and are written to the database. If they are on the database any attempt to enter the application fails with sqlcode 1690 BIGINT UNSIGNED out of range. The only way to solve this is to remove the affected row from table bfstop_bannedip with the database administration tool.

Regards,
Hermann Kauffeld

**Comment by codeling** [comment]
Thanks for reporting!
I unfortunately didn't yet have time to test bfstop it on an ipv6 system, but will make it a priority. Can't make any promises on time schedule yet unfortunately, as I have hardly any t ime to dedicate to bfstop at the moment.

**Comment by codeling** [comment]
What I found out so far that the only really viable solution for doing proper subnet matching with IPv6 is using INET6_ATON (which was introduced with MySQL 5.6.3 only, which I surely can not add as prerequisite to install my plugin).

I will probably have to disable subnet matching for IPv6, as implementing a workaround for this seems a tad too compex and error prone to me at the moment.
I have to check whether I maybe can determine the mysql server version, and enable the subnet checks if version >= 5.6.3 is present.

**Comment by codeling** [comment]
With https://github.com/codeling/bfstop/commit/2b01a441da3329d14e94c5102b19cbdb118a1246 , IPv6  CIDR suffix notation is now not checked anymore for matches.

Full IPv6 support will be introduced with version 1.5.0.
