### ISSUE TITLE
Warning during updates

### ISSUE THREAD

**Issue by WebfootDesigns** [codeling/bfstop#118]
Hello, when we run updates, clear cache, and find updates, we receive this error message:
Could not open update site #14 "BFStop Package Update Server"
Can you help us clear this warning?
![bruteforce](https://cloud.githubusercontent.com/assets/17007868/13373703/62918682-dd34-11e5-8134-ac8f0bec6774.jpg)

**Comment by codeling** [comment]
Hello and thanks for the report,
but this has already been reported before, see https://github.com/codeling/bfstop/issues/95 (this has information how to fix it) and https://github.com/codeling/bfstop/issues/116
