### ISSUE TITLE
My server shows only one public IP

### ISSUE THREAD

**Issue by santo1227** [codeling/bfstop#125]
Hi, 

My server shows only one public IP (cloud service), if an user it's blocked, the block it's for all users at the same time.

Do you have any advice for this?

Regards

**Comment by codeling** [comment]
Sorry for the late comment.
This sounds like you are behind some kind of load balancer or reverse proxy.
There was a change recently which should handle this situation better (https://github.com/codeling/bfstop/commit/f3b476888e461c0d4b33f26135d35d894410a72a).
Unfortunately there is no release yet with this fix in it. Until it is released you could try the "daily snapshot version" from https://github.com/codeling/bfstop/archive/master.zip
