### ISSUE TITLE
Joomla 3.5.1 - language - PLG_SYSTEM_BFSTOP_PASSWORD_RESET_RECOMMENDED

### ISSUE THREAD

**Issue by ZerooCool** [codeling/bfstop#126]
J'ai un bogue sur cette action :

PLG_SYSTEM_BFSTOP_PASSWORD_RESET_RECOMMENDED="Au moins une tentative de connexion a récemment échoué. En multipliant les essais infructeux, vous risquez d'être bientôt bloqués pour des raisons de sécurité. Raison pour laquelle nous vous recommandons de <  a href='%1'>réinitialiser votre mot de passe<  /a>!"

(LES ESPACES < a>  <  /a> sont volontaires, pour afficher le code source. )

J'obtiens chez moi : 
PLG_SYSTEM_BFSTOP_PASSWORD_RESET_RECOMMENDED="Au moins une tentative de connexion a récemment échoué. En multipliant les essais infructeux, vous risquez d'être bientôt bloqués pour des raisons de sécurité. Raison pour laquelle nous vous recommandons de

Rien de plus :/
J'ai tenté \'  \'    et, seulement  =%1  mais, rien n'y fait.
Avez vous une idée ?

Au fait !!! Le site est actuellement HORS LIGNE !!!
( Sans le master .htaccess )
Cela peut expliquer que %1 ne s'affiche pas ?

Mais, pour l'envoie de mail qui ne marche pas ?
Est ce due au problème avec la mise à jour de Joomla! 3.5.1 qui à cassé l'envoie des mails ?

Je pense que ce sont la 2 questions très intéressantes, par avance merci à ceux d'entre vous qui pourraient apporter des éléments de réponse.

**Comment by codeling** [comment]
Hi, I'm sorry I don't really speak french; I hope you will also understand my english answer.
From what I gathered through my very basic french and google translate is that you're having two problems:
(1) a truncated message
(2) mails are not working

Problem (2) (or both?) have started with 3.5.1? I am not aware of any special things in Joomla 3.5.1 that would make bfstop fail there, but haven't checked in detail yet.

What I did not get was the part about your site being offline, what do you mean by that? Is it offline because of bfstop or because of some other reason?

**Comment by ZerooCool** [comment]
PB 1 : My web site is offline, not a problem only test mode offline.
I have test with the site online, but, the same problem.

I have Delete %1 I use only texte now.
PLG_SYSTEM_BFSTOP_PASSWORD_RESET_RECOMMENDED="Votre première tentative de connexion a échoué. Nous vous recommandons de changer votre mot de passe si la deuxième tentative reste en échec. Multiplier les essais ne sert à rien. Vous risquez simplement d'être bloqués pour des raisons de sécurité en cas de troisième tentative infructueuse."

PB 2 :  I am not aware of any special things in Joomla 3.5.1 ...
*Ok, Joomla 3.5.1 have a big serious problem, the Update have destroy a lot mail capacity to send.
It's a very big bogue, from Joomla! 3.5.1 ... I don't know more ...

New Problem, PB 3
From Backend admin : 
Unknown column 'l.error' in 'field list' SQL=SELECT l.id, l.username, l.ipaddress, l.error, l.logtime, l.origin FROM #__bfstop_failedlogin l ORDER BY l.id ASC LIMIT 0, 20

**Comment by codeling** [comment]
> Ok, Joomla 3.5.1 have a big serious problem, the Update have destroy a lot mail capacity to send.

So this is a general problem with Joomla 3.5.1? Good to know.

regarding PB3: which bfstop version are you running? The latest one from the git repository, or a "release" version as linked to [on the Download page](https://github.com/codeling/bfstop/wiki/Download%20and%20Installation)?

**Comment by ZerooCool** [comment]
PB2 yes you anderstand good. Mails not work is a Joomla! Problem.

I have active the log, i see nothing. I have purge all log, i test now if i can see.

Version :
Brute Force Stop
	Administration 	Composant 	1.3.0 	May 2013 	Bernhard Froehler
System - Brute Force Stop
	Site 	Plug-in 	1.3.0 	November 2012 	Bernhard Froehler

**Comment by ZerooCool** [comment]
OK Friends ! Stop all ! I deleted this and install the same, the PACKAGE from GIT.
After i delete the application bruteforce composant and plugin, I can't install the second installation, this file exist : 
/administrator/manifests/packages/pkg_bfstop.xml
I need delete this. Ok.

I install, work it.
I test, i come back.

**Comment by ZerooCool** [comment]
Perfect !
PB1 Resolwed with the good package from GITHUB. (Joomla! Installeur have not the good package ??)

PB3 All panel Admin Back end are working.
The test email say that'is good too.
Le test de notification semble s'être déroulé correctement. Néanmoins, veuillez vérifier que vous avez également reçu le courriel de test à l'adresse électronique indiquée ci-dessus.

PB2 I Look my email.
Ohoh Yes lot spam :x) Work perfect !

R E S O L V E D - E N J O Y !
N I C E > J O B <

**Comment by codeling** [comment]
Good to know that this is fixed with the newest version. I had hoped to push that out a long time ago already, but just don't have the time at the moment. Will try to do it soon!
