### ISSUE TITLE
brute force stop has has blocked an ip, now all access from outside the network is blocked from accessing the site

### ISSUE THREAD

**Issue by zikhali** [codeling/bfstop#128]
brute force stop on joomla has has blocked an ip, now all access from outside the network are blocked from accessing the site. 

all sites trying to access the site are blocked with this message "Your IP address has been blocked because there were too many unsuccessful login attempts in a short time. Your IP address is: xx.xxx.xx.xx.''

where xx.xxx.xx.xx is an ip address that is blocked. Please assist

**Comment by codeling** [comment]
I suspect your Server to be behind a reverse proxy / load balancer, and xx.xxx.xx.xx is that Machine. There was some work recently to allow for this but it hans't made it into a released Version yet. See here for more details: https://github.com/codeling/bfstop/issues/125

**Comment by codeling** [comment]
Without more information there is nothing more I can do; I have to assume the information provided before was enough to resolve the problem, thus I'm closing this issue!
