### ISSUE TITLE
How i can see the alerte WARNING with a other menu connexion BT Login Module

### ISSUE THREAD

**Issue by ZerooCool** [codeling/bfstop#130]
I don't have the alert, with the module BT Login.
Then, with the normal connexion module, bfstop work good with a popup alerte, WARNING.

With a other connexion module, i don't see the popup WARNING .... 5 test .... 4 test .... 3 test ... you are blocked ... This popup, the user not see, with the BT Login module. -> bowthemes.com/bt-login-module

This mod is nice, please, look this, if you have the time.

**Comment by codeling** [comment]
This probably means that this BT login module doesn't show the message placeholder.
Nothing I can do here. I just add the warnings through proper Joomla API's. Please report this with the BT login module.

**Comment by ZerooCool** [comment]
Hum Ok, i test send this issue to the BTLoginModule Team.
