### ISSUE TITLE
php7 compatibility

### ISSUE THREAD

**Issue by madmaxy** [codeling/bfstop#135]
Hi,

i want to change my Joomla 3.6. to php7.
Is your version 1.3.0 working with php7?

Thanks and the best

**Comment by codeling** [comment]
1.3.0 is not yet working with php7, see https://github.com/codeling/bfstop/issues/133, https://github.com/codeling/bfstop/issues/124 .
You could try with the latest development snapshot (https://github.com/codeling/bfstop/wiki/Specific%20Versions#latest-development-snapshot).
I am trying to get a new release out of the door but unfortunately the time I have for bfstop is very limited at the moment.

**Comment by codeling** [comment]
bfstop will work on php version 7 in the upcoming version 1.4.0, it will be released in a few days!
