### ISSUE TITLE
ip wildcard

### ISSUE THREAD

**Issue by walldorff** [codeling/bfstop#143]
Is it possible to block IP's by wildcard (like 109.* or 109.86.*) ?

**Comment by codeling** [comment]
Wildcard notation is not supported, but the CIDR suffix notation is, with which you can achieve the same.

To block 109.*, enter "109.0.0.0/8" in the IP address field, to block 109.86.*, you'd have to enter "109.86.0.0/16".

There is also [an FAQ entry](https://github.com/codeling/bfstop/wiki/FAQ#can-i-blockwhitelist-a-subnet--ip-range) for this.

**Comment by walldorff** [comment]
Thank you! I read the FAQ, butdid not realize that it could also be used as wildcard :)

**Comment by codeling** [comment]
I'll adapt the FAQ entry to make it more clear, thanks for the feedback!
