### ISSUE TITLE
Warning: BFStop Package Update Server

### ISSUE THREAD

**Issue by rippleau** [codeling/bfstop#148]
We ran the Joomla! updater and received this **Warming**:

> Update: Could not open update site #10 "BFStop Package Update Server", URL: https://raw.github.com/codeling/pkg_bfstop/master/update.xml

The above URL is dead. Any ideas?

**Comment by codeling** [comment]
My bad.
I had changed the URL for 1.4.0/1.4.1, and hadn't thought that the 1.3.0 still referenced it. Should be fixed now!

**Comment by rippleau** [comment]
Thanks 👍 
Just getting the update now :)
