### ISSUE TITLE
Erweiterungen: Aktualisieren

### ISSUE THREAD

**Issue by schwartzmarkt** [codeling/bfstop#149]
Warnung
Update: :Extension: „https://bfstop.bfroehler.info/update-pkg.xml“ kann nicht geöffnet werden!

Fehler
Ungültiges Erweiterungsupdate

**Comment by codeling** [comment]
Which Version of bfstop did you have installed before?
(welche Version von bfstop hatten Sie zuvor installiert?)

**Comment by schwartzmarkt** [comment]
Joomla 3.6.5
bfstop 1.3.0 und 1.4.0 -> gleiche Fehlermeldung

**Comment by schwartzmarkt** [comment]
Joomla 3.6.5
bfstop 1.3.0 und 1.4.0 -> gleiche Fehlermeldung

**Comment by codeling** [comment]
I neither can reproduce this error message for a fresh Joomla!/bfstop install nor for an upgraded Joomla! installation. Do you get this only for bfstop or also for other extensions? Entries on the web with this error message which I have found so far in a quick search (e.g. http://blog.florian-felgenhauer.de/2012/02/ungultiges-erweiterungsupdate-bei-joomla-update/) point in direction of some problems during Joomla! upgrades possibly causing this.

(Ich kann diese Fehlermeldung weder für eine neue Joomla!/bfstop Installation, noch für eine upgedatete Joomla!-Installation nachvollziehen. Bekommen Sie diese Meldung nur für BFstop oder auch für andere Erweiterungen? Bei den Erwähnungen dieser Fehler-Meldung, die ich bei einer kurzen Suche entdecken konnte (http://blog.florian-felgenhauer.de/2012/02/ungultiges-erweiterungsupdate-bei-joomla-update/), scheint es sich um Probleme mit dem Joomla!-Upgrade-Prozess gehandelt zu haben.

**Comment by schwartzmarkt** [comment]
der Fehler tritt nur bei der bfstop Erweiterung auf, andere Erweiterungsupdates funktionieren problemlos (the error only comes up on the bfstop extention, other extention update work without any problems)

**Comment by schwartzmarkt** [comment]
by the way, the manual update uploading the .zip file (pkg_bfstop-1.4.0.zip or pkg_bfstop-1.4.1zip) works fine ...

**Comment by codeling** [comment]
At the moment I unfortunately don't have an idea where this message could come from unfortunately:
The XML available under https://bfstop.bfroehler.info/update-pkg.xml should be valid, and in all my test installations, the automatic update has worked and hasn't shown this problem.
One more thing that comes into mind that could make a difference is the php version, which one are you using?

**Comment by schwartzmarkt** [comment]
here is some more details on 2 different php version having the same error:

PHP 7.0.15

1.4.0 -> 1.4.1:
Update: Die Aktualisierungsquelle #18 „BFStop Package Update Server“ konnte nicht geöffnent werden! URL: https://bfstop.bfroehler.info/update.xml

Systeminformationen

PHP erstellt für			Linux schwartzmarkt.eu 2.6.32-358.11.1.el6.x86_64 #1 SMP Wed Jun 12 03:34:52 UTC 2013 x86_64
Datenbankversion			5.5.54
Datenbankzeichensatz			utf8_general_ci
Datenbankverbindungszeichensatz		utf8mb4_general_ci
PHP-Version				7.0.15
Webserver				Apache
PHP-Interface für den Webserver		cgi-fcgi
Joomla!-Version				Joomla! 3.6.5 Stable [ Noether ] 1-December-2016 22:46 GMT
Joomla!-Plattform-Version		Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Browsererkennung			Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

===================================================================

PHP 5.6.30

1.4.0 -> 1.4.1:
Update: Die Aktualisierungsquelle #23 „BFStop Package Update Server“ konnte nicht geöffnent werden! URL: https://bfstop.bfroehler.info/update.xml

Systeminformationen
 
PHP erstellt für			Linux schwartzmarkt.eu 2.6.32-358.11.1.el6.x86_64 #1 SMP Wed Jun 12 03:34:52 UTC 2013 x86_64
Datenbankversion			5.5.54
Datenbankzeichensatz			utf8mb4_general_ci
Datenbankverbindungszeichensatz	utf8mb4_general_ci
PHP-Version				5.6.30
Webserver				Apache
PHP-Interface für den Webserver		cgi-fcgi
Joomla!-Version				Joomla! 3.6.5 Stable [ Noether ] 1-December-2016 22:46 GMT
Joomla!-Plattform-Version		Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Browsererkennung			Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by codeling** [comment]
When exactly does this message appear? When going to the extension updates pages, or after trying to start the update?

Also, this is a slightly different message than what you reported initially, when is that initial message (Ungültiges Erweiterungsupdate) shown?

**Comment by schwartzmarkt** [comment]
this one is shown after surching for the update and before the update is startet.

**Comment by schwartzmarkt** [comment]
ok, before this gets asleep, here is something new out of a brand new joomla installation (3.6.5) and trying to install bf 1.4.1 out of the extention catalog, maybe this helps to locate the problem:

Warnung

Fehler beim Verbindungsaufbau zum Server: SSL connect error

Fehler

Ungültige URL
Es kann kein Installationspaket gefunden werden!

**Comment by codeling** [comment]
That's now three different error messages, the last one even specifying three different messages; really strange.

SSL connect error would suggest some problem with the SSL certificate on bfstop.bfroehler.info. Yet I cannot see any problems with it, see e.g. https://www.ssllabs.com/ssltest/analyze.html?d=bfstop.bfroehler.info

Ungültige URL (Invalid URL) - No idea what that could refer to; as it doesn't give the URL it considers invalid (and the one given in previous messages (https://bfstop.bfroehler.info/update-pkg.xml), definitely is valid (just try to enter it in a browser, you will get presented the xml file.

"Es kann kein Installationspaket gefunden werden" seems, when checking for that message e.g. on the Joomla! forum, also seems to be more or less a "catch-all" message, where typically the accompanying other message gives details (Invalid URL in this example I guess). So this also doesn't give more information.

Unfortunately I really can't tell you what's wrong here at the moment.

What system are you running these installations on, is it the same linux distribution or different ones?

**Comment by schwartzmarkt** [comment]
The installation are all running on the same server under CentOS 6.6 (Final)‬. I also just noticed that there is two different updatesites:

BFStop Package Update Server	
https://raw.github.com/codeling/pkg_bfstop/master/update.xml
Brute Force Stop Package	Site	Paket	Unbekannt	7
		
BFStop Package Update Server	
https://bfstop.bfroehler.info/update.xml
Brute Force Stop Package	Site	Paket	Unbekannt	23

but the first one seem to be the older one and it doesn't show an updateinformation.

the funny thing, and this is what might be a ssl encryption problem is that even if it shows me:

Update: Die Aktualisierungsquelle #23 „BFStop Package Update Server“ konnte nicht geöffnent werden! URL: https://bfstop.bfroehler.info/update.xml

it still shows me the update information:

Name	Bereich	Typ	Installiert	Verfügbar	Verzeichnis	Installationstyp	URL-Details
	
Brute Force Stop Package
Site	Paket	1.4.0	1.4.1	Unbekannt	Aktualisierung	https://bfstop.bfroehler.info/update-pkg.xml	

but trying to update this one brings me back to the error message I postet the first time ...

**Comment by nesshoever** [comment]
Pretty much the same here. All extensions are updated fine except bfstop (from 1.3.0 to 1.4.1)
Any update on that matter at all?

**Comment by codeling** [comment]
@nesshoever what operating system / distribution is your server running?

**Comment by codeling** [comment]
@schwartzmarkt 
regarding the two different update sites:
you are right, https://raw.github.com/codeling/pkg_bfstop/master/update.xml is the old one.
I probably should introduce a setup script to remove this one during upgrade as it is redundant to https://bfstop.bfroehler.info/update.xml, and has caused problems in the past, with Joomla! not being able to follow the redirect that github apparently uses internally for such URLs.

**Comment by nesshoever** [comment]
@codeling It a shared env at my hoster:
Apache Version: 2.4.12
PHP Version: 5.5.25
MySQL Version: 5.5.52-cll
Architecture:  x86_64
Operating System: linux
Perl Version: 5.8.8
Kernel Version: 2.6.18-471.3.1.el5.lve0.8.72xen

I have three separate Joomla 3.6.5 installations and al three reprted the same issue. The manual upload and installation of the latest ZIP was successful. If a manually access the update xml URL, I get a proper resposne, but Joomla reports on all three instances: "Update: Die Aktualisierungsquelle „BFStop Package Update Server“ konnte nicht geöffnent werden! URL: https://bfstop.bfroehler.info/update.xml"
I checked the update sources and there are two entries for your plugin:
https://bfstop.bfroehler.info/update.xml and https://raw.github.com/codeling/pkg_bfstop/master/update.xml
The github one seems to be the older one. Should both entries exist?

**Comment by codeling** [comment]
> The github one seems to be the older one. Should both entries exist?

As I said in my previous post, the github one is outdated and can be deleted. I'll look into deleting it with the next upgrade.

But as for why this error occurs, I have no idea. I cannot reproduce it on my test systems.

**Comment by codeling** [comment]
@schwartzmarkt 
I'm trying to look into this in more detail the moment, and am wondering, whether there is a specific reason why not the most recent version from the 6.x branch in CentOS is in use?
As far as my research into that distribution (which I haven't used so far) shows, the minor version updates should come automatically, and at the time of the post that 6.6 was in use, 6.8 should have been the current one ? Did I get something wrong here, are the intermediate releases also supported for a longer time?

**Comment by codeling** [comment]
@schwartzmarkt 
I'm trying to look into this in more detail the moment, and am wondering, whether there is a specific reason why not the most recent version from the 6.x branch in CentOS is in use?
As far as my research into that distribution (which I haven't used so far) shows, the minor version updates should come automatically, and at the time of the post that 6.6 was in use, 6.8 should have been the current one ? Did I get something wrong here, are the intermediate releases also supported for a longer time?

**Comment by codeling** [comment]
I now set up a Virtual Machine with CentOS 6(.9, upgraded from a 6.6 with yum install), and used the following guide to get the php version 5.6.31: https://webtatic.com/packages/php56/)

I then installed bfstop 1.4.0.
The 1.4.1 release showed up in the updates section immediately afterwards.
I have done a snapshot before the upgrade to 6.9, will test again if it's something specific to 6.6 next...

**Comment by codeling** [comment]
On CentOS 6.6 I indeed get an SSL connection error when I try to connect to a site signed with letsencrypt (which above-referenced bfroehler.info pages are).

So the solution to this is simple: Update to an up-to-date version of CentOS, or at least update the trusted certificates store to include letsencrypt!
