### ISSUE TITLE
htaccess file not in root of site

### ISSUE THREAD

**Issue by digitalarchitects** [codeling/bfstop#150]
Using a sub-dir is not supported, perhaps a config item could allow for the htaccess file to be in a parent directory.

**Comment by codeling** [comment]
The .htaccess considered by bfstop is the one placed in the Joomla! root folder - this should block all access to Joomla!.
I am not aware that a .htaccess is not effective in a subfolder? If you would like to block a user from not only Joomla! but your whole server, then I'd actually recommend using a different tool (maybe phpids? but really not an expert here).

**Comment by digitalarchitects** [comment]
My Joomla is in a sub folder of the apache root so I will move it to the root so it works.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by codeling** [comment]
What do you mean by " I will move it to the root so it works. "  - what exactly does _not_ work at the moment, what symptoms are you experiencing? The .htaccess file, even if it resides in a subfolder, is theoretically still able to block access to your Joomla! installation.

What I think forgot to address properly, though, is the fact that the .htaccess file **has to exist** for bfstop to be able to add things to it. So maybe simply creating an empty .htaccess file in the Joomla! will fix your issue?

**Comment by codeling** [comment]
Two action items for me for the next version:
- Provide some support for creating the .htaccess file
- Provide an option to specify the .htaccess location

**Comment by digitalarchitects** [comment]
Hi,
Perhaps I need to explain properly. I have multiple web sites in a single hosting server. The sub-domains are pointed to sub-directories and each Joomla is working fine there because the htaccess file is “local” or in the root folder of the web site for that domain.

The root site is empty and the main “domain” for management is redirected to a subfolder so that it doesn’t interfere with the other sites. This means that it’s htaccess file is actually in a parent directory, which the joomla install cannot see.

I have installed the main joomla into the root directory and the error has now gone. I will see how this affects my other admin etc.

I agree on the two points, specifically the second one, as it would have meant I could leave my dir structure as it was.

Thanks

**Comment by codeling** [comment]
> This means that it’s htaccess file is actually in a parent directory, which the joomla install cannot see.

You mean there is a single .htaccess which exists already, and you want bfstop to share it among all Joomla! installations, do I get that correctly?

> and the error has now gone

What exact error - do you mean the notice in bfstop about not being able to use blocking via .htaccess?

**Comment by digitalarchitects** [comment]
Yes the error about not being able to use Htaccess blocking. I was not actually wanting to share the Htaccess blocking across the other sites. It suits me to have to install the plugin in each instance so I can have different lists in each especially white lists.

It is really just the management domain that was 'special' as the Htaccess file is in the parent. Apache has rights to see it but the plugin would not usually look there.

I think stick to your two suggestions for now. We can investigate shared Htaccess lists across sites in the future or leverage a blacklisting service to prepopulate the lists.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by codeling** [comment]
> so I can have different lists in each especially white lists.

Please note that .htaccess blocking completely bypasses the whitelisting.

> It is really just the management domain that was 'special' as the Htaccess file is in the parent.

What is the "management domain"? Do you mean the root folder of your apache installation?

> I think stick to your two suggestions for now. We can investigate shared Htaccess lists across sites in the future or leverage a blacklisting service to prepopulate the lists.

You mean across multiple different webservers? A global blacklist, possibly distributed by some server?

**Comment by digitalarchitects** [comment]
Perhaps the best thing is to explain that I have a webhosting account with a Cpanel interface with webhosting hub. Installations of web sites are done via the softculous menu and are a template of the latest wordpress etc.

This is very common across many web site hosting companies.

The plugin seems to struggle with this as there are many installations in sub-directories of a shared apache virtual server.

What the best solution is, is up for debate!

Regards,

Kevin Wilson
General Manager IT Services

+27 11 552 4093 (Office)
+27 82 901 4224 (Mobile)
+27 86 676 6065 (DigiFax)

Stefanutti Stocks Corporate Services
a division of Stefanutti Stocks (Pty) Ltd
Reg No. 2003/022221/07

[cid:image001.png@01D2F64F.0A0C4030]<http://http/www.stefanuttistocks.com/?utm_source=email_signature&utm_medium=email_sig_click&utm_campaign=internal>
[cid:image002.png@01D2F64F.0A0C4030]
See link to Disclaimer below:
http://www.stefanuttistocks.com/Email-Disclaimer.aspx
