### ISSUE TITLE
Adding ACL in the back-end component 

### ISSUE THREAD

**Issue by ukphotoguy** [codeling/bfstop#154]
Been a fan and user of this component for a long time and it has worked well for me and my clients. Just been setting up a back-end access for a specific type of admin and trying to restrict their access to just the component they need. Fortunately for me all my component providers play by the Joomla ACL rules except BFStop. This is regrettable and I feel bad raising the issue.  But because I cannot set permissions for this component I cannot restrict who has administrator access. In my case this means my appointments calendar administrator can also see and change the bf stop settings. Probably not a big deal but nevertheless something that can be fixed relatively simply.
So before I start on a hack, would BFStop be planning adding just the basic level of ACL control by adding the option to restrict administrator access to the component view? Personally, I do not see the need for all the levels of control but it probably all comes as a package if you use the recommended Joomla approach. https://docs.joomla.org/Adding_ACL_rules_to_your_component.
regards steve

**Comment by codeling** [comment]
For sure that's something that should be supported, thanks for pointing it out! To my shame I have to say I simply wasn't aware of this yet. I'll add it in the next version.

**Comment by codeling** [comment]
I did look into ACL, and a basic one is already provided by the current BFStop component; you can determine which user group can access the BFStop administration and which can not (Extensions -> Manage -> Manage, click Options on the upper right, then go to the "Permissions" tab, select "Brute Force Stop Administration" on the left, and you will be able to configure which user group can access the brute force stop backend.

As the linked article has information about how to restrict access to certain rows or fields (as far as I understand it), is it a more fine-grained control that you need? If so, could you describe in a bit more detail what you're trying to achieve?

**Comment by ukphotoguy** [comment]
small typo on the bfstop.php addition, obviously should be if (!JFactory::getUser()->authorise('core.manage', 'com_bfstop'))
not com_com_bfstop

**Comment by codeling** [comment]
@ukphotoguy not sure which bfstop.php addition you're referring to, In the linked commit I see none?

**Comment by ukphotoguy** [comment]
sorry comment should be attached to the codeling/com_bfstop@f29a964 thread where I posted the code.

**Comment by codeling** [comment]
Thanks for your contribution, and thhank for the posted code!
I wasn't aware that additional checks are necessary to restrict access.
I reviewed it and tested it, it looks good, it's added now (https://github.com/codeling/com_bfstop/commit/7233ac996997ddff7389d59904dd19ec92758ed2) and will be released soon!
