### ISSUE TITLE
www.hami.tehran.ir

### ISSUE THREAD

**Issue by kazemiarezou** [codeling/bfstop#157]

**Comment by kazemiarezou** [comment]
i am IP address has been blocked because there were too many unsuccessful login attempts in a short time.

**Comment by kazemiarezou** [comment]
Your IP address has been blocked because there were too many unsuccessful login attempts in a short time.

**Comment by kazemiarezou** [comment]
i am IP address has been blocked because there were too many unsuccessful login attempts in a short time.

**Comment by codeling** [comment]
From the notification emails I got about this issue I take it that you were blocked ("i am IP address has been blocked because there were too many unsuccessful login attempts in a short time.")... on your own site? More details please ;)

**Comment by codeling** [comment]
Without any details I cannot help you. Please report a full description of your problem if it persists.
