### ISSUE TITLE
permanent block doesn't work

### ISSUE THREAD

**Issue by oryxnl** [codeling/bfstop#159]
After a selectable number of temporary blocks, the block should become permanent. 
This feature seems not to work. There are several IP's in the temporary block list that were blocked more often than the treshold set for a permanent block but these still get a temporary block.

**Comment by oryxnl** [comment]
Update: finally the permanent block appeared after 4 previous temporary blocks. The treshold is set at 2 however. It could be that I changed the treshold from (intially) 4 to 2, but I'm not sure about that.

**Comment by codeling** [comment]
I will try do some testing on that in the next few days. Ideally you could try around on your end a bit too if you can reproduce this problem?

**Comment by codeling** [comment]
As I haven't heard back I assume this issue was not reproducible? Closing it for now, feel free to reopen if it reoccurs
