### ISSUE TITLE
Can't override language

### ISSUE THREAD

**Issue by danielbidala** [codeling/bfstop#162]
My intranet site is always offline, only members can login. I created hu-HU language folder to override en-GB but it takes no effect. Also I tried to modify plugin en-GB language file but with no luck. Nothing happen the blocked IP message and remaining attempts message are the same. Any idea?

**Comment by codeling** [comment]
As for the hu-HU language folder, you might have to enter it in the manifest file (bfstop.xml) to work.

Why a modification to the en-GB language file wouldn't help I can't tell you, this should work. 

For the blocked IP message you however don't need to change the language file, it can be configured in the plugin settings (in the Joomla! menu, select Extensions->Plugins, then type "Brute" and click on the search button, then click on "System - Brute Force Stop", and there on the "Advanced" tab, you can configure it. (*With the upcoming 1.5 version, due some time hopefully still this year, this settings will be also available in the "Components -> Brute Force Stop" section). As for the remaining attempts message, this can indeed only be configured in the language file (the PLG_SYSTEM_BFSTOP_X_ATTEMPTS_LEFT line , in e.g. the en-GB.plg_system_bfstop.ini file as you probably have figured out already).

Have you cleared all caches (server side and client side) when you did those experiments)?

**Comment by danielbidala** [comment]
Thanks for your reply. I added hu-HU to bfstop.xml. But it seems to work only when language debug is enabled. When I turn it off, just the default en-GB message shown, also if I modify the default en-GB language files. Joomla 3.8.1!

**Comment by codeling** [comment]
> Please try to test with offline mode on.

Could you elaborate what you mean by "offline mode", how did you configure that? The only option I know of in that direction is what's called "Website offline" in the Joomla! configuration, but that disables the Joomla! frontend completely; are you doing that and only using the backend (/administrator subfolder)?

**Comment by danielbidala** [comment]
Yes I use "website offline" function. It don't disable frontend. This way users must login to see frontend of the website which in fact is an online application and there is no public part of it. Only users with access can login to frontend too.

**Comment by codeling** [comment]
OK, I see, in the website offline functionality that I remember there was no login functionality; so my memory is a bit outdated. I will try that later today.

What you could try is copying the adapted version of the en-GB / hu-HU folder  from the plugin folder to the system-wide language folder; not sure if [this pull-request](https://github.com/joomla/joomla-cms/pull/17372) is already included in the Joomla! core, but from what I read there, it seems like the way the Joomla! language file are included has been modified lately (and wasn't consistent across core). Why a direct modification of the language file wouldn't be considered though escapes me. Did you try searching the Joomla! folder whether there maybe is another copy of the bfstop language files somewhere?

**Comment by codeling** [comment]
To make the long story short; bfstop installs the language files also to the system-wide language folder (e.g. plugins/system/bfstop/language/en-GB/en-GB.plg_system_bfstop.ini); those override the language files in the plugin folder (e.g. administrator/language/en-GB/en-GB.plg_system_bfstop.ini).

So, change the files in administrator/language/en-GB, and your changes will be visible!

For future versions of bfstop, I will look into whether only installing into the extension folder works, so to avoid the double files, and the confusion you experienced here!

**Comment by codeling** [comment]
Starting with 1.5.0, the administrator/language files will no longer be installed, see 51f451d3 .

I will not delete the files on an upgrade though (or I would possibly remove already modified versions), so unless you do a fresh installation on a new system, you will still want to modify the language files in the administrator/language folder
