### ISSUE TITLE
How to hide my host name

### ISSUE THREAD

**Issue by ghost** [codeling/bfstop#163]
When i exceed  threshold i saw my host name and error403. But i want to hide my host name. How to solve this problem.

**Comment by codeling** [comment]
>  i saw my host name

Where? In the block message? I guess you mean the IP address as bfstop doesn't show any hostnames anywhere as far as I can tell?
The ip address display can be disabled in the settings:
Go to Joomla! Backend: Extensions -> Plugins -> System - Brute Force Stop; in the "Advanced" tab you will find a "Show IP" checkbox.

**Comment by codeling** [comment]
As the account asking the question was deleted I'm assuming his question was solved...
