### ISSUE TITLE
Error message when clicking on blocked IP address in Blocked IPs Database Page

### ISSUE THREAD

**Issue by giando23** [codeling/bfstop#170]
When I click on any IP address listed in IPs Database page I get the following error message:

Warning: count(): Parameter must be an array or an object that implements Countable in /homepages/.................../views/ipinfo/view.html.php on line 16
No information available for that IP address

Any idea why it is happening?

**Comment by codeling** [comment]
Yes, this is the same issue as reported here: https://github.com/codeling/bfstop/issues/169

I will try to fix it with the next release, but I can't guarantee that this will be anytime soon. If you need info on those ip addresses, for now you will need to manually use one of the many available geo ip services.
