### ISSUE TITLE
Username not shown for front-end failed logins

### ISSUE THREAD

**Issue by afa4ii** [codeling/bfstop#171]
On failed logins Brute Force Stop is not showing the username for front end failed logins, only shows the back end failed login username

**Comment by codeling** [comment]
bfstop should track the username for both cases (and does so for me); out of the top of my head I cannot think of a reason at the moment why it would not do that.
Do you maybe see [any errors in your webserver or bfstop log](https://github.com/codeling/bfstop/wiki/FAQ#what-can-i-do-if-something-doesnt-work-as-expected) that could indicate what is going wrong here? It also might be something specific to the kind of server you are using - what is your server configuration?

**Comment by afa4ii** [comment]
Linux with godaddy


Jack
AFA4II/AFR4D
webmaster afmarsR4.org
Digital Networks Manager  Region 4



________________________________

**Comment by codeling** [comment]
I just realized in another issue that the Login module does not enforce the username to be set. Could it be that these attempts simply had an empty username? If you have problems with your template, it could also be that users are "forced" into submitting empty usernames, see also this issue: https://github.com/codeling/bfstop/issues/175

**Comment by codeling** [comment]
Without more information I cannot do anything here, and will close the issue. If it should still happen, please reopen and provide the info asked for above!
