### ISSUE TITLE
Invalid IP Address

### ISSUE THREAD

**Issue by fastraks** [codeling/bfstop#173]
I don't think this is a BFStop issue but I am a little out of my league. Hostgator updated their EasyApache to 4 a few weeks ago. Now my site with bfstop is logging and blocking login attempts with the server ip address. I noticed that when I look at the x_forwarded_for it shows only the server IP when I am connecting with https so I think it is a hostgator error. I looked for the Forwarded variable but it is blank.

**Comment by codeling** [comment]
No idea about this EasyApache stuff, but probably some kind of proxy / loadbalancer setup. If the newest version doesn't get you the real IP, I have no idea ...

**Comment by g5macdaddy** [comment]
I have all my site with Hostgatpor as well and I am having this same issue I believe. Not sure what i can do other then disable the plugin.

**Comment by codeling** [comment]
There isn't really anything I can do either, unfortunately.
If there is no way to get the "real" client IP, then bfstop can not do its work.
 I'll have to close this issue as I can't fix it from my side.
