### ISSUE TITLE
Message "X attempt(s) left before your IP address will be blocked" shall be Warning

### ISSUE THREAD

**Issue by kofaysi** [codeling/bfstop#174]
Dear Bernhard,

Issue: I suggest that information about the number of attempts left shall be Warning (yellow). Currently it is of type Message (green).
![Screenshot_2020-05-12 Společenství vlastníků Světova 523 - Společenství vlastníků Světova 523](https://user-images.githubusercontent.com/17022173/81648210-9a847580-942e-11ea-8eae-6c52eb56a4ce.png)

Enhancement: Additionally, towards 2 and 1 attempt left information could be displayed as Error (red) to enhance visibility and recognition by user.

Explanation: Green color suggest a positive information and may be ignored by a user. 

Thank you for the great work!

(minor edit)

**Comment by codeling** [comment]
Good suggestion, I will add it in the next version!

**Comment by kofaysi** [comment]
Thank you for considering and pushing forward!
