### ISSUE TITLE
Compatibility with Joomla ‎4

### ISSUE THREAD

**Issue by Goalfair** [codeling/bfstop#177]
After Joomla upgrade to Joomla ‎4.0.0-beta6 (bfstop was installed prior to upgrade):

**Error accessing the component options:**
`Class 'JSubMenuHelper' not found`

**Error on fresh install of extension:**
`Call to undefined method Joomla\CMS\Installer\Adapter\PluginAdapter::get() `

**Error on enabling the plugin:**
`Call to undefined method Joomla\Database\Mysqli\MysqliDriver::getErrorNum() `

Last message then stays, joomla dashboard is basically toast.

I likt this plugin, is it going to be compatible with Joomla 4? Thanks!

**Comment by codeling** [comment]
Compatibility with Joomla 4.0 is on my To-Do list. I had lost track of it a bit though, so thanks for bringing it up! Is the release date for 4.0 already known?

**Comment by Goalfair** [comment]
According to their roadmap, there is no fixed release date (yet): https://developer.joomla.org/roadmap.html#4

But good to know this plugin is still supported, I like the ease of use.

**Comment by gaasen** [comment]
I too is a big fan of BFStop so it is highly appreciated that you continue support of this fabulous extension.

Regards
Goran

**Comment by codeling** [comment]
Just checked - the latest master should already be _mostly_ compatible with Joomla 4.

It's not exactly trivial to install it directly, so I will do a release in the upcoming days or latest weeks to push this out (1.4.2 or 1.5.0)

**Comment by codeling** [comment]
com_bfstop now also runs without errors on Joomla 4 (with https://github.com/codeling/com_bfstop/commit/4cf47f34b952a6c300c29980f9eeb7462e532925).
