### ISSUE TITLE
0 Call to a member function getData() on bool

### ISSUE THREAD

**Issue by otpfiste** [codeling/bfstop#178]
When updating to 1.4.2 a table issue was shown, sorry I did not take a screenshot. Now when pressing the Options button the following is displayed:
![bfstoperror](https://user-images.githubusercontent.com/886348/115579147-2bfa9980-a2c6-11eb-8f95-beaee59442ca.png)

**Comment by mrjuke4859** [comment]
I am also getting the same error.

**Comment by codeling** [comment]
Thanks for reporting this!

Yes I've seen the table issue you mention on one of my test systems, I think it's not critical - it's about a table that get's renamed during the upgrade (probably it gets renamed just before the old code is called for one last time, but I have to look some more into that).

Regarding the error on going to the component options, I found the mistake - I forgot to add the config.xml file for the component.

A workaround is possible but unfortunately a bit of a hassle:
- Download [pkg_bfstop-1.4.2.zip](https://bfstop.bfroehler.info/releases/pkg_bfstop-1.4.2.zip)
- Extract the com_bfstop.zip file from within the packages subfolder in pkg_bfstop-1.4.2.zip
- Extract the config.xml file from within admin subfolder in com_bfstop.zip
- Upload the config.xml (e.g. via FTP) to the administrator/components/com_bfstop subfolder of your Joomla! installation.

If you're willing to wait, I will push a release with a fix for this included in the next couple of weeks.

**Comment by codeling** [comment]
Should be fixed by https://github.com/codeling/com_bfstop/commit/3422a0d0fbc4fea06a94484ff44e2839005fe5b3.
