### ISSUE TITLE
Can‘t add entry to Exception List

### ISSUE THREAD

**Issue by Jumanji1010** [codeling/bfstop#183]
Hi there,
great tool, works fine so far with one exception:
Trying to add an entry to the Exception List will result in an error:

Es ist ein Fehler aufgetreten!
0 Call to a member function getKeyName() on bool

best regards
J.

**Comment by codeling** [comment]
Please see https://github.com/codeling/bfstop/issues/181 and https://github.com/codeling/bfstop/issues/182.
