### ISSUE TITLE
Adaptive Delay bugged?

### ISSUE THREAD

**Issue by LuxLOL** [codeling/bfstop#188]
Hi,
I thing the "Adaptive Delay" option isn't working. Because if I enable it then the wafting time to login will not increase.

**Comment by codeling** [comment]
If I have time I'll set up some tests for it. How are you testing it?

Could you describe your testing procedure?

Note also that this is implemented in a "global" way - meaning that the delay grows the more failed login attempts there currently are for the whole site. It's not an increasing delay for each sequential login atttempt from a single location...

**Comment by LuxLOL** [comment]
I tested it by doing 6 failed logins attempts, but nothing changes. If I set the Fixed Delay to 15 then I have to wait 15 seconds before I get logged in.

**Comment by codeling** [comment]
> I tested it by doing 6 failed logins attempts, but nothing changes. If I set the Fixed Delay to 15 then I have to wait 15 seconds before I get logged in.

Did you take a closer look at the plugin configuration? especially at the tooltips of the *Minimum threshold* / *Maximum threshold* parameters. In a default configuration with *Minimum threshold*=50, *Maximum threshold*=200, you will of course not notice any delay on 6 attempts - the delay only kicks in when 50 failed attempts are noticed **per hour** and will reach the *Maximum delay* at 200 failed attempts per hour.

> I also didn't know that this option is a global setting. Would be nice to make it IP based. Otherwise this can be easily be abused by anyone.

Abused how exactly? Successful logins or normal page use is not delayed. The setting is actually more or less targeted at slowing down a distributed attack (as typically happens these days, only very few failed logins / attempts come from the same IP). And only a **failed** login will be delayed.

**Comment by LuxLOL** [comment]
Ahh. Looks like I got the options a bit mixed up. I now retried it and it looks like the daily will increase after 25 failed login attempts. So everything is fine. :D
