### ISSUE TITLE
BfStop don't handle phpmailer exception

### ISSUE THREAD

**Issue by pgizest** [codeling/bfstop#193]
Hello,

I'm currently migrating to joomla4. For that, i have a VM (locally) in which I know i'm not able to send mail (with phpmailer or sendmail).
When i log in frontend, when i'm in joomla 3.10, in case of bad user/password, i've got  a message indicating that mail doesn't work 
(see first attached file)
However, when doing the same in joomla 4, i've got an exception in php mailer.
And when i disable the bfstop plugin, i don't have the problem.

I tried to use a more recent template (cassiopae), but it's the same

![Login_J310](https://user-images.githubusercontent.com/126449070/221499525-930949a2-a3bb-4831-a615-437de9aa51f1.png)
![Login_J42](https://user-images.githubusercontent.com/126449070/221499636-978319b5-7bd1-4154-a8e6-743c6f1160e2.png)

**Comment by codeling** [comment]
Thanks for the report; I will try to reproduce the problem and get back to you in the next days.
Just for completeness, I don't see the screenshots / attached files you mention.

**Comment by pgizest** [comment]
Yes i can disable the notification, but it's important to know which of my user failed to login (this is old person that i know, not very familiar with computer)

**Comment by pgizest** [comment]
Hello,
I have added the screenshot now
Regards

**Comment by codeling** [comment]
> but it's important to know which of my user failed to login

You would still have the failed login attempts listed in the backend; and I meant you can disable it only for the test system; this would in any case only be a temporary workaround, and generally such an error shouldn't happen.

**Comment by codeling** [comment]
This is more complicated to handle than I thought. Joomla internally catches email sending problems, and enqueues error messages (and probably also the shown stack trace, not sure about that one yet) automatically. This means that to prevent the mesesages, I currently see two options:

1. Change the Joomla core to make it possible to tell the email sending functionality to optionally be silent about errors (and get those changes to be accepted into a future version of Joomla) - not sure if core developers would look favorably on this.
2.  or reimplement Joomla's mail functionality  - a complex endeavour, which would mean that bfstop would have code more or less duplicated from Joomla core, and that code would have to be adapted to each change of the mail system in core.

Both options don't look very attractive to me at the moment; I'll have to think a bit more about this.
