### ISSUE TITLE
Is BFSTOP compatible with Joomla 5?

### ISSUE THREAD

**Issue by Jumanji1010** [codeling/bfstop#201]
Hi there,

is BFSTOP compatible with Joomla 5?

Thanks!

**Comment by codeling** [comment]
I have not been able to test on Joomla 5, but plan to do so soon. I'll put it in for the next version (1.5.0).

**Comment by codeling** [comment]
Quick initial tests suggest that at least the latest main branch of both plugin and component are working fine. I'll have to do some more thorough tests though and also update the manifest and update files accordingly!

**Comment by codeling** [comment]
Looking at JED Checker results, it does require the backwards compatibility plugin at the moment. I will keep this ticket open until all issues reported b JED checker for J5 compatibility are fully fixed.

**Comment by codeling** [comment]
With commits [78592b8c (plugin)](https://github.com/codeling/bfstop/commit/78592b8c422b14ee275d169296da765e725845fe) and [5aba1582 (component)](https://github.com/codeling/com_bfstop/commit/5aba15822a4632bbed90d545f13d0d5a7955fc05), bfstop is now Joomla 5 compatible; that is, it runs without the compatibility plugin.

These will be released in the upcoming version 1.5.0 in the next days.
