### ISSUE TITLE
Deprecated: Creation of dynamic property plgSystembfstop::$notifier is deprecated PHP8.2

### ISSUE THREAD

**Issue by kevinalderton** [codeling/bfstop#209]
Hi. Will there be an update to cover the deprecation in php8.2? 
Deprecated: Creation of dynamic property plgSystembfstop::$notifier is deprecated in plugins/system/bfstop/bfstop.php on line 193.

Many thanks

**Comment by codeling** [comment]
Yes, there will be (see issue #197 already solved in the main branch), which will be included in the [upcoming version 1.5.0](https://github.com/codeling/bfstop/milestone/15) which is unfortunately a little delayed due to time issues.
