### ISSUE TITLE
Litespeed

### ISSUE THREAD

**Issue by wowakan** [codeling/bfstop#210]
Hello,

I am using Litespeed and getting this error:
Warning
You're either not using apache server, or the .htaccess file either does not exist, or it is not read- or writeable. Blocking via .htaccess will not work.

Will this work with Litespeed?

Kind Regards,
RBaker

**Comment by codeling** [comment]
> Will this work with Litespeed?

I have not had the chance to test bfstop with litespeed (and currently no time/plans to do so in the near future). The test is, as it says, only checking whether bfstop is running on an apache server. At the time I wrote these checks I was not aware if there are other webservers supporting such files - do you by any chance know of such a list?

If that message is shown, it does not mean that .htaccess definitely will not work. The checks are only meant as a hint for users in case blocking doesn't work.

So, I would recommend to test whether it works in your case. I'd be happy to extend the check to include litespeed if you can report that it works!

**Comment by codeling** [comment]
@wowakan did you get around to test this on litespeed?

**Comment by codeling** [comment]
@wowakan I am closing this because I have no time to explore and test litespeed capabilities myself. Feel free to comment and reopen if you find time to do so yourself.
