### ISSUE TITLE
Allow using .htaccess for blocking

### ISSUE THREAD

**Issue by codeling** [codeling/bfstop#74]
It was suggested that blocking via .htaccess instead of blocking via database could be highly advantageous in terms of performance.

This would have to be an optional alternative of course, since not every environment running Joomla! will allow blocking htaccess directives.

**Comment by codeling** [comment]
Basic functionality implemented with commit 1874878b3673f21840f539e34d90b139ea488cb5 .
Did some load tests with JMeter as well, and it looks very promising regarding performance boost:
5 threads / repetition until stable throughput established.
plain joomla: 28/sec
bfstop blocking (via db): 30/sec
htaccess blocking: 1800/sec
(tested on my slow development server machine, an Atom D520).

Note: Editing/Removing is not yet implemented. Will create a separate issue for this.
Note 2: Thanks @tgv604 for your comment. Will have to take special care to avoid concurrency issues

**Comment by codeling** [comment]
@jpkleemans I'd love to use your .htaccess blocking code! Since it's GPL'ed I guess it should be fine, but I thought I'd ask anyway - are you fine with that ;)? You will of course be properly referenced. Thanks in advance!

**Comment by jpkleemans** [comment]
That's fine! Thanks for asking. Good luck with your plugin! :+1:

**Comment by euoceo** [comment]
Am I missing something or does this code basically just append to the end of .htaccess? So these entries will never time out? This works as a quick-fix, but the preferr method would be to keep track of .htaccess changes and rewrite it as others mention. 

Also from my observation (and others), if you run Apache, this is definitely the way to go. I have several Wordpress sites that put captchas in the login, but when a bot hits this and never gives up the system load goes way up. I found a WP plugin that uses .htaccess to block and now the load sticks around .05 when being hit. I would recommend taking a look at that WordPress plugin as a model for your .htaccess rewrite code. What it does is put a Begin/End like tag line around it's modifications, rereads .htaccess strips the old Begin/End out and rewrites the new Begin/End always at the top of .htaccess. Here's a sample of that (It has several sections, I'm just showing the section that pertains to this thread):

#AIOWPS_BASIC_HTACCESS_RULES_START
#AIOWPS_IP_BLACKLIST_START
Order allow,deny
Allow from all
Deny from 209.126.70.184
Deny from 217.8.245.128
Deny from 87.195.107.217
#AIOWPS_IP_BLACKLIST_END
#END All In One WP Security

The normal .htaccess code then follows this. I checked the code's license and it is GPL, so possibly this is something that can be used. It'll allow you to observed whitelist/blacklist and real time adds and expiration times too as you basically just rewrite .htaccess whenever one of those events kick in.

Plugin home page: https://www.tipsandtricks-hq.com/wordpress-security-and-firewall-plugin

Everything to write .htaccess looks to be self-contained in a class called AIOWPSecurity_Utility_Htaccess in the file /classes/wp-security-utility-htaccess.php under the plugin's directory. There's lots of extra stuff, but I'm sure the concept and the code can be stripped down to just the basics that are needed. If you are short of time, I'm willing to help out with this.

It's worth taking a look at some of the other options this plugins does too, such as writing rules to block access to .htaccess/wp-config.php/debug files/etc.

**Comment by codeling** [comment]
Haven't checked in detail yet but what you mention might be the same that I linked to above, and yes the plan for the next release is to use the class from there or sth. Similar. Thanks for the pointers!

**Comment by euoceo** [comment]
Ah, I missed the link. I've actually used that plug-in as well for some of my other WordPress sites, pretty much the same concept. One or the other should be fine and a great improvement to bfstop for sure!

**Comment by jpkleemans** [comment]
Hi @codeling, I've created a package on GitHub for .htaccess blocking with PHP. See https://github.com/jpkleemans/htaccess-firewall.
It has better code, and is much better tested then the current Htaccess class in my WP plugin.
Maybe you can use it for your plugin. Feedback is always welcome!

**Comment by codeling** [comment]
@jpkleemans sounds great, I hope to have a chance to test this in the next few days!
