### ISSUE TITLE
Wrong subject & body in notification

### ISSUE THREAD

**Issue by PaulCyberEngel** [codeling/bfstop#84]
When I get a notification I get "BLOCKED_IP_ADDRESS_SUBJECT" for the subject and "BLOCKED_IP_ADDRESS_BODY" for the body.  When I send a test notification it comes through correctly.

**Comment by codeling** [comment]
Is this still occuring?
As a workaround has somebody tried to upgrade the php version? From the reports I've seen it only occurs on php 5.2, so an upgrade to a later version could fix it.

**Comment by BrucklynBoy** [comment]
Yes. Still occuring. I have three systems, all running on PHP 5.2, but on 2 different providers. The two running on the same provider work fine, the single one running at one of Germanys huge providers is not :(

**Comment by codeling** [comment]
Sorry to not have gotten back to you earlier on this.
I unfortunately still have no clue at all at where this could come from, and therefore also now how to reproduct it.

I still suspect something with php version and /or configuration to be the reason.
Therefore I would recommend to try upgrading php (or get your hoster to). Version 5.2 is hopelessly outdated, and does not get any updates or security fixes anymore (http://php.net/eol.php). Any responsible hoster should upgrade to at least version 5.5.

**Comment by codeling** [comment]
@BrucklynBoy @PaulCyberEngel Any luck with php upgrades? Have you encountered this problem with any php version newer than 5.2? If not I will close this as being a problem with too old php versions.

**Comment by codeling** [comment]
As servers running supported versions of php don't seem to be affected by this issue, I will close it.
