### ISSUE TITLE
Your IP address er blocked 

### ISSUE THREAD

**Issue by prefalch** [codeling/bfstop#91]
I've got the problem that I can not access my page, get this message: 

Your IP address er blocked because there were too many unsuccessful login forsøger in a short time. 

Is there an option to stop bute force temporary so I can come in and set it up properly.

With regards

Preben

**Comment by codeling** [comment]
@prefalch Since I didn't hear back from you I suppose one of the methods worked, so I will close this. If you should still encounter it please reopen.

**Comment by prefalch** [comment]
Sorry that I did not answer, the way in FAQ work
