### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by dpi92** [codeling/bfstop#97]
hi 
I wrote my mail adresse in the bforce configuraten.
But when i send a testmail, i don't get a mail.
I also tried to set the notification to my user but nothing happens.
Did I forgett something in the configuration?
Thnks for your help

**Comment by codeling** [comment]
Did you try the "test notification" function in the "Brute Force Stop Administration" component? Are there any messages when you do that?
Are there maybe any messages in the bfstop log file? See here for details on logging: https://github.com/codeling/bfstop/wiki/FAQ#how-do-i-turn-on-logging

**Comment by euoceo** [comment]
I would also start with whether you have Joomla configs setup
    properly and if you are getting notifications from other Joomla
    components.
    
    Under "Global Configuration->Server" set "Send mail" to "yes" and
    "Mailer" to "PHP Mail".  That should work, unless your host have PHP
    Mail disabled, then you can try on of the other methods. You'll know
    sending mail is working on the server by Setting
    "Users->Options->Notification Mail to Administrators" to "Yes"
    and then adding a dummy user account and see if you get a
    notification, if you do, then you'll know sending mail is working
    and can then narrow the problem down to bfstop itself.
    
    On 1/23/2015 3:49 AM, dpi92 wrote:
    
    
      hi 
        I wrote my mail adresse in the bforce configuraten.
        But when i send a testmail, i don't get a mail.
        I also tried to set the notification to my user but nothing
        happens.
        Did I forgett something in the configuration?
        Thnks for your help
      —
        Reply to this email directly or view it on
          GitHub.

**Comment by dpi92** [comment]
Thanks!
That was the problem.
