### ISSUE TITLE
Blocking any IP which tries the "admin" account / username...

### ISSUE THREAD

**Issue by ThiloSO** [codeling/bfstop#98]
Hi there,

first off all: Really nice Package! Have it installed on every Joomla installation! Thanks for your efforts.

An idea: 
When i look at my sites it's always bots trying the old, standard "admin" account with different passwords. Since probably no one who seriously wants to secure ones site, is using that name anymore, wouldn't it be the following a good optional feature to include:

Any attempt with the usage "admin" (as username) is blocked right away.
If there isn't any account with that name, there is no need to let the bots bothering the server :- )

Greets,

Thilo

**Comment by codeling** [comment]
Good idea, I had something similar in mind already: https://github.com/codeling/bfstop/issues/76

It's described a bit more generic there, but a specific admin rule would definitely be a good start. I'll close this in favor of above linked issue, if  you have any objections let me know.
